version: '2'
services:
  postgis:
    build: ./postgis
    volumes:
      - ./postgis/postgresql.conf:/etc/postgresql/postgresql.conf
      - /Users/lucky/data:/var/lib/postgresql/data
      - ./pbf:/pbf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_DB=gis
    restart: unless-stopped
  renderer:
    build: ./renderer
    volumes:
      - ./renderer/map_data:/map_data
      - ./renderer/scripts:/scripts
    volumes_from:
      - postgis:ro
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - postgis
    restart: unless-stopped
  web:
    image: nginx:alpine
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
    depends_on:
      - renderer
    restart: unless-stopped
